<?php
defined( 'ABSPATH' ) || exit;

$GLOBALS['powered_cache_options'] = array (
  'enable_page_cache' => true,
  'object_cache' => 'off',
  'cache_mobile' => true,
  'cache_mobile_separate_file' => false,
  'loggedin_user_cache' => false,
  'ssl_cache' => true,
  'gzip_compression' => false,
  'cache_timeout' => 1440,
  'auto_configure_htaccess' => true,
  'rejected_user_agents' => '',
  'rejected_cookies' => '',
  'vary_cookies' => '',
  'rejected_uri' => '',
  'ignored_query_strings' => '',
  'cache_query_strings' => '',
  'purge_additional_pages' => '',
  'minify_html' => false,
  'minify_html_dom_optimization' => false,
  'combine_google_fonts' => false,
  'swap_google_fonts_display' => true,
  'use_bunny_fonts' => false,
  'minify_css' => false,
  'combine_css' => false,
  'critical_css' => false,
  'critical_css_additional_files' => '',
  'critical_css_excluded_files' => '',
  'critical_css_appended_content' => '',
  'critical_css_fallback' => '',
  'excluded_css_files' => '',
  'remove_unused_css' => false,
  'ucss_safelist' => '',
  'ucss_excluded_files' => '',
  'minify_js' => false,
  'combine_js' => false,
  'excluded_js_files' => '',
  'js_execution_method' => 'blocking',
  'js_defer' => false,
  'js_defer_exclusions' => '',
  'js_delay' => false,
  'js_delay_exclusions' => '',
  'js_execution_optimized_only' => true,
  'rewrite_file_optimizer' => true,
  'enable_image_optimization' => false,
  'image_optimizer_preferred_format' => '',
  'add_missing_image_dimensions' => false,
  'enable_lazy_load' => false,
  'lazy_load_post_content' => true,
  'lazy_load_images' => true,
  'lazy_load_iframes' => true,
  'lazy_load_widgets' => true,
  'lazy_load_post_thumbnail' => true,
  'lazy_load_avatars' => true,
  'lazy_load_skip_first_nth_img' => 3,
  'disable_wp_lazy_load' => false,
  'disable_wp_embeds' => false,
  'disable_emoji_scripts' => false,
  'enable_cdn' => false,
  'cdn_hostname' => 
  array (
    0 => '',
  ),
  'cdn_zone' => 
  array (
    0 => '',
  ),
  'cdn_rejected_files' => '',
  'enable_cache_preload' => false,
  'preload_homepage' => true,
  'preload_public_posts' => true,
  'preload_public_tax' => true,
  'enable_sitemap_preload' => false,
  'preload_sitemap' => '',
  'prefetch_dns' => '',
  'preconnect_resource' => '',
  'prefetch_links' => true,
  'db_cleanup_post_revisions' => false,
  'db_cleanup_auto_drafts' => false,
  'db_cleanup_trashed_posts' => false,
  'db_cleanup_spam_comments' => false,
  'db_cleanup_trashed_comments' => false,
  'db_cleanup_expired_transients' => false,
  'db_cleanup_all_transients' => false,
  'db_cleanup_optimize_tables' => false,
  'enable_scheduled_db_cleanup' => false,
  'scheduled_db_cleanup_frequency' => 'daily',
  'enable_cloudflare' => false,
  'cloudflare_api_token' => '',
  'enable_heartbeat' => false,
  'heartbeat_dashboard_status' => 'enable',
  'heartbeat_dashboard_interval' => 60,
  'heartbeat_editor_status' => 'enable',
  'heartbeat_editor_interval' => 15,
  'heartbeat_frontend_status' => 'enable',
  'heartbeat_frontend_interval' => 60,
  'enable_varnish' => false,
  'varnish_ip' => '',
  'cache_footprint' => true,
  'async_cache_cleaning' => false,
  'enable_google_tracking' => false,
  'enable_fb_tracking' => false,
  'cache_location' => 'C:\\xampp1\\htdocs\\zdrava_hrana\\wordpress/wp-content/cache/',
);

$powered_cache_mobile_browsers = '2.0 MMP, 240x320, 400X240, AvantGo, BlackBerry, Blazer, Cellphone, Danger, DoCoMo, Elaine/3.0, EudoraWeb, Googlebot-Mobile, hiptop, IEMobile, KYOCERA/WX310K, LG/U990, MIDP-2., MMEF20, MOT-V, NetFront, Newt, Nintendo Wii, Nitro, Nokia, Opera Mini, Palm, PlayStation Portable, portalmmm, Proxinet, ProxiNet, SHARP-TQ-GX10, SHG-i900, Small, SonyEricsson, Symbian OS, SymbianOS, TS21i-10, UP.Browser, UP.Link, webOS, Windows CE, WinWAP, YahooSeeker/M1A1-R2D2, iPhone, iPod, Android, BlackBerry9530, LG-TU915 Obigo, LGE VX, webOS, Nokia5800';
$powered_cache_mobile_prefixes = 'w3c , w3c-, acs-, alav, alca, amoi, audi, avan, benq, bird, blac, blaz, brew, cell, cldc, cmd-, dang, doco, eric, hipt, htc_, inno, ipaq, ipod, jigs, kddi, keji, leno, lg-c, lg-d, lg-g, lge-, lg/u, maui, maxo, midp, mits, mmef, mobi, mot-, moto, mwbp, nec-, newt, noki, palm, pana, pant, phil, play, port, prox, qwap, sage, sams, sany, sch-, sec-, send, seri, sgh-, shar, sie-, siem, smal, smar, sony, sph-, symb, t-mo, teli, tim-, tosh, tsm-, upg1, upsi, vk-v, voda, wap-, wapa, wapi, wapp, wapr, webc, winw, winw, xda , xda-';
$powered_cache_rejected_user_agents = array (
  0 => 'facebookexternalhit',
);
$powered_cache_rejected_cookies = array (
  0 => 'wp-postpass',
  1 => 'wordpressuser_',
  2 => 'wordpresspass_',
  3 => 'wordpress_sec_',
  4 => 'wordpress_logged_in_',
  5 => 'powered_cache_commented_posts',
  6 => 'comment_author_',
  7 => 'comment_author_email_',
  8 => 'comment_author_url_',
);
$powered_cache_vary_cookies = array (
);
$powered_cache_rejected_uri = array (
);
$powered_cache_ignored_query_strings = array (
  0 => 'fbclid',
  1 => 'fb_action_ids',
  2 => 'fb_action_types',
  3 => 'ref',
  4 => 'gclid',
  5 => 'fb_source',
  6 => 'utm_source',
  7 => 'utm_medium',
  8 => 'utm_campaign',
  9 => 'utm_term',
  10 => 'utm_content',
  11 => 'utm_expid',
  12 => '_ga',
  13 => 'mc_cid',
  14 => 'mc_eid',
  15 => 'campaignid',
  16 => 'adgroupid',
  17 => 'adid',
  18 => 'age-verified',
  19 => 'usqp',
  20 => 'cn-reloaded',
  21 => 'ao_noptimize',
);
$powered_cache_cache_query_strings = array (
);
$powered_cache_slash_check = true;
